version: "3"

services:


  api:
    build: .
    restart: always
    environment:
      - PYTHONPATH=.
    volumes:
      - ./:/app:z
      - ./logs:/app/logs:z
    ports:
      - 127.0.0.1:3005:8000
    networks:
      - network


networks:
  network:
  default:
    external:
      name: docker_default
